# Tensorflow Matrix Math Exercises

In [1]:

import tensorflow as tf
import numpy as np

In [2]:
sess = tf.InteractiveSession()

NOTE on notation
* _x, _y, _z, ...: NumPy 0-d or 1-d arrays
* _X, _Y, _Z, ...: NumPy 2-d or higer dimensional arrays
* x, y, z, ...: 0-d or 1-d tensors
* X, Y, Z, ...: 2-d or higher dimensional tensors

## Matrix Math Functions

Q1. Create a diagonal tensor with the diagonal values of x.

In [7]:
_x = np.array([1, 2, 3, 4])
x = tf.convert_to_tensor(_x)


[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


Q2. Extract the diagonal of X.

In [8]:
_X = np.array(
[[1, 0, 0, 0],
 [0, 2, 0, 0],
 [0, 0, 3, 0],
 [0, 0, 0, 4]])
X = tf.convert_to_tensor(_X)


[1 2 3 4]


Q3. Permutate the dimensions of x such that the new tensor has shape (3, 4, 2).

In [9]:
_X = np.random.rand(2,3,4)
X = tf.convert_to_tensor(_X)


(3, 4, 2)


Q4. Construct a 3 by 3 identity matrix.

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


Q5. Predict the result of this.

In [3]:
_X = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
X = tf.convert_to_tensor(_X)

diagonal_tensor = tf.matrix_diag(X)
diagonal_part = tf.matrix_diag_part(diagonal_tensor)

print("diagonal_tensor =\n", diagonal_tensor.eval())
print("diagonal_part =\n", diagonal_part.eval())


Q6. Transpose the last two dimensions of X.

In [4]:
_X= np.random.rand(1, 2, 3, 4)
X = tf.convert_to_tensor(_X)



Q7. Multiply X by Y.

In [13]:
_X = np.array([[1, 2, 3], [4, 5, 6]])
_Y = np.array([[1, 1], [2, 2], [3, 3]])
X = tf.convert_to_tensor(_X)
Y = tf.convert_to_tensor(_Y)


[[14 14]
 [32 32]]


Q8. Multiply X and Y. The first axis represents batches.

In [14]:
_X = np.arange(1, 13, dtype=np.int32).reshape((2, 2, 3))
_Y = np.arange(13, 25, dtype=np.int32).reshape((2, 3, 2))
X = tf.convert_to_tensor(_X)
Y = tf.convert_to_tensor(_Y)



[[[ 94 100]
  [229 244]]

 [[508 532]
  [697 730]]]


Q9. Compute the determinant of X.

In [15]:
_X = np.arange(1, 5, dtype=np.float32).reshape((2, 2))
X = tf.convert_to_tensor(_X)



-2.0


Q10. Compute the inverse of X.


In [16]:
_X = np.arange(1, 5, dtype=np.float64).reshape((2, 2))
X = tf.convert_to_tensor(_X)



[[-2.   1. ]
 [ 1.5 -0.5]]
